language: r
dist: trusty
cache: packages
sudo: required

r_packages:
 - devtools
 - testthat
 - covr

after_success:
 - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - r: oldrel 
    - r: release
    - r: devel

